if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  include(MSVC)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  include(GNU)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  include(Clang)
endif()
message (STATUS "CMAKE COMPILER ID : ${CMAKE_CXX_COMPILER_ID}")

if(CMAKE_SIZEOF_VOID_P MATCHES 8)
    set(PLATFORM "64")
    MESSAGE(STATUS "Detected 64-bit platform")
elseif(CMAKE_SIZEOF_VOID_P MATCHES 4)
    set(PLATFORM "32")
    MESSAGE(STATUS "Detected 32-bit platform")
endif()
